---

# Get keys from https://ftp-master.debian.org/keys/
- name: Update apt-keys
  apt_key:
    url: https://ftp-master.debian.org/keys/archive-key-11.asc
    state: present
  tags:
    - apt
  become: yes

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt
  become: yes

- name: Apt upgrade
  apt:
    upgrade: safe
    update_cache: yes
    #dpkg_options: "force-confdef,force-confold,a"
    cache_valid_time: 3600
  tags:
    - apt
  notify:
    - Reboot host

- name: Apt remove
  apt:
    purge: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt
  notify:
    - Reboot host

- name: Apt cleanup
  apt:
    purge: yes
    autoclean: yes
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt
  notify:
    - Reboot host
