---
all:
  hosts:
    localhost:
      host_ip: 127.0.0.1
      ansible_connection: local
      ansible_user: mattcozzolino
      ansible_python_interpreter: /usr/local/bin/python3
    nginx.dc.cozzo.net:
#      host_name: NGINX
#      host_domain: dc.cozzo.net
      #ansible_user: svc-ansible
      host_ip: 10.11.14.11
#  vars:
#    ansible_python_interpreter: /Users/mattcozzolino/Library/Python/3.7/bin
