---
all:
  hosts:
    localhost:
      host_ip: 127.0.0.1
      ansible_connection: local
      ansible_user: mattcozzolino
      ansible_python_interpreter: /usr/local/bin/python3
  children:
    nginx:
      hosts:
        nginx.dc.cozzo.net:
          ansible_host: 10.11.14.11
    downloader:
      hosts:
        downloader01.dc.cozzo.net:
          ansible_host: 10.11.14.31
        downloader02.dc.cozzo.net:
          ansible_host: 10.11.14.32
        downloader03.dc.cozzo.net:
          ansible_host: 10.11.14.33
    plex:
      hosts:
        plex.dc.cozzo.net:
          ansible_host: 10.11.14.30
    dev:
      hosts:
        test.dc.cozzo.net:
          ansible_host: 10.11.14.41
