---

- name: Connect to managed zone
  google.cloud.gcp_dns_managed_zone:
    #name: managedzone-rrs
    name: "{{ gcp_zone }}"
    dns_name: "{{ gcp_dns_name }}"
    description: test zone
    #project: "cozzo-dns"
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    #service_account_file: "../vars/cozzo-dns-8f248ebc58f2.json"
    service_account_file: "{{ gcp_vars_file }}"
    #service_account_file: "/Users/mattcozzolino/GitHub/vars/cozzo-dns-8f248ebc58f2.json"
    #project: "{{ gcp_project }}"
    #auth_kind: "{{ gcp_cred_kind }}"
    #service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: gcp_managed_zone

- name: Examine the challenge data
  debug:
    #msg: '{{ item | map(attribute="challenge_data") }}'
    #msg: '{{ item | map(attribute="module_args")|map("dictsort")|flatten }}'
    #msg: '{{ item|map("dictsort") }}'
    #msg: '{{ item + " || " + challenge_changed }}'
    msg: '{{ item.1 }}'
    #msg: '{{ challenge_changed }}'
    #msg: '{{ item.1.resource + " /\/\ " + item.1.resource_value }}'
    #dest: "/mnt/docker/blue/nginx80/www/cozzo.net/htdocs/{{ item.1.resource }}"
    #content: "{{item.1.resource_value }}"
    #msg: "{{ acme_challenge.results }}"
    #msg: "{{ challenge_data }}"
    #msg: "{{ challenge_domains[*] }}"
  vars:
    challenge_data: '{{ hostvars["nginx.dc.cozzo.net"].acme_challenge.results|map(attribute="challenge_data")|map("dictsort")|flatten }}'
    challenge_domains: '{{ challenge_data[::2] }}'
    challenge_resources: '{{ challenge_data[1::2]|map(attribute="dns-01")|list }}'
  #loop: '{{ acme_challenge.results }}'
  #loop: '{{ challenge_domains|zip(challenge_resources)|zip(challenge_changed)|list }}'
  loop: '{{ challenge_domains|zip(challenge_resources)|list }}'
  #loop: '{{ challenge_changed }}'
  #when: acme_challenge[my_idx].changed
  loop_control:
    #label: '{{ item.0 }}'
    index_var: my_idx
  tags:
    - always

- name: Clean up DNS records
  google.cloud.gcp_dns_resource_record_set:
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_vars_file }}"
    managed_zone: "{{ gcp_managed_zone }}"
    type: TXT
    ttl: 300
    name: "{{ item.1.record }}."
    #name: nginx.cozzo.net.
    #target: "{{ item.1.resource_value }}"
    #target: SdqZBq7eMTleXs-ilAi1nQm7dZSK-7yxQ8xa1-O7eM4
    #- 10.1.1.1
    #- 10.2.2.2
    state: absent
  vars:
    challenge_data: '{{ hostvars["nginx.dc.cozzo.net"].acme_challenge.results|map(attribute="challenge_data")|map("dictsort")|flatten }}'
    challenge_domains: '{{ challenge_data[::2] }}'
    challenge_resources: '{{ challenge_data[1::2]|map(attribute="dns-01")|list }}'
  #loop: '{{ acme_challenge.results }}'
  #loop: '{{ challenge_domains|zip(challenge_resources)|zip(challenge_changed)|list }}'
  loop: '{{ challenge_domains|zip(challenge_resources)|list }}'
  #loop: '{{ challenge_changed }}'
  #when: acme_challenge[my_idx].changed
  loop_control:
    #label: '{{ item.0 }}'
    index_var: my_idx


#- name: Place challenge data in htdocs
#  copy:
#    dest: "/mnt/docker/blue/nginx80/www/cozzo.net/htdocs/{{ item.1.resource }}"
#    content: "{{item.1.resource_value }}"
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
#    # owner: root
#    # group: root
#    #when: ansible_facts['os_family'] == "Debian"
#  vars:
#    challenge_data: '{{ acme_challenge.results|map(attribute="challenge_data")|map("dictsort")|flatten }}'
#    challenge_changed: '{{ acme_challenge.results|map(attribute="challenge_data")|map("dictsort")|flatten }}'
#    challenge_domains: '{{ challenge_data[::2] }}'
#    challenge_resources: '{{ challenge_data[1::2]|map(attribute="http-01")|list }}'
#  loop: '{{ challenge_domains|zip(challenge_resources)|list }}'
#  loop_control:
#    label: '{{ item.0 }}'
#  tags:
#    - never
#    - install
#    - update
#    - generate
#    - acme
