---

################################################################################
# Environment setup
# Conainer root throughout the environment. 
container_root: "/mnt/docker/configs"
proxy_servers:
  - name: "dc.cozzo.net"
    #host: "rproxy.dc.cozzo.net"
    app: "caddy.dc.cozzo.net"
    #ip: "10.11.14.11"
  - name: "camp.cozzo.net"
    #host: "rproxy.camp.cozzo.net"
    app: "caddy.camp.cozzo.net"
    #ip: "10.21.2.15"  

################################################################################
# GCP config
# GCP dns name requires the trailing period site.com.
gcp_dns_name: cozzo.net.
gcp_vars_file: ../../vars/cozzo-dns-8f248ebc58f2.json
gcp_project: cozzo-dns
gcp_zone: cozzonet

################################################################################
# Local DNS
# 
#dns01_server: http://dns01.dc.cozzo.net:5380 # no trailing /
#dns01_token: ----


################################################################################
# Site config
# The giant array that conatins all of the proxy matching. 

# LB: caddy.dc.cozzo.net = CNAME:dc.cozzo.net       = A:x.x.x.x
# App: app.dc.cozzo.net  = CNAME:srv.dc.cozzo.net   = A:x.x.x.x

## DNS Schema
# The application directly. Use this with the specific port number. Or the IP of the server. 
# [       docker_app         ]        [    docker_host      ]
# homeassistant.camp.cozzo.net CNAME: docker05.camp.cozzo.net 
#
# Proxied names of the server. This is the traditional 80>443 redirect. Uses LE to generate certs on the proxy server. 
# [      proxy_urls          ]        [proxy_server]  [         proxy_pass            ]
# homeassistant.cozzo.net      CNAME:  proxy_server > homeassistant.camp.cozzo.net:1234
# camp-homeassistant.cozzo.net CNAME:  proxy_server > homeassistant.camp.cozzo.net:1234
# ha.cozzo.net                 CNAME:  proxy_server > homeassistant.camp.cozzo.net:1234
# etc...

apps:
#############################################################
#  - name: "ha"                                       #Name of the service (Doesn't actually get used?)
#    docker_app: "homeassistant.camp.cozzo.net"       # FQDN of the app. CNAME to <docker_host> It will also end up getting passed as: docker-compose -f <docker_app> up -d 
#    docker_host: "docker05.camp.cozzo.net"           # Where does the host run. Reflects an A recrod
#    proxy_urls:                                      # Valid certificate alt names. Also CNAME to <proxy_server>
#      - "homeassistant.cozzo.net"
#      - "ha.cozzo.net"
#      - "camp-ha.cozzo.net"
#    proxy_pass: "homeassistant:8123"                 #Matches the container name for inter container dns. Entry in the caddyfile for the site. 
#    #proxy_pass: "homeassistant.camp.cozzo.net:8123" #FQDN if needed.  
#    proxy_server: "camp.cozzo.net"                   # <proxy_urls> CNAME: <proxy_server> 
#    proxy: true                                      # Make an entry
#    public: true                                     # Public or private

# Camp
  - name: "ha"
    docker_app: "homeassistant.camp.cozzo.net" 
    docker_host: "docker05.camp.cozzo.net" 
    proxy_urls: # Proxy config
      - "homeassistant.cozzo.net"
      - "ha.cozzo.net"
      - "camp-ha.cozzo.net"
    #proxy_pass: "homeassistant.camp.cozzo.net:8123"
    proxy_pass: "homeassistant:8123" #Matches the container name because I moved to common container networking. 
    proxy_server: "camp.cozzo.net" 
    proxy: true
    public: true

  - name: "zwave"
    docker_app: "zwave.camp.cozzo.net" 
    docker_host: "docker05.camp.cozzo.net" 
    proxy_urls: 
      - "zwave.cozzo.net"
      - "camp-zwave.cozzo.net"
    #proxy_pass: "zwave.camp.cozzo.net:8091"
    proxy_pass: "zwave-js-ui:8091"
    #proxy_pass: "10.21.2.15:8091"
    proxy_server: "camp.cozzo.net" 
    proxy: true
    public: false

  - name: "nodered"
    docker_app: "nodered.camp.cozzo.net" 
    docker_host: "docker05.camp.cozzo.net" 
    proxy_urls: 
      - "nodered.cozzo.net"
      - "camp-nodered.cozzo.net"
    proxy_pass: "nodered:1880"
    proxy_server: "camp.cozzo.net" 
    proxy: true
    public: false

  - name: "mosquitomqtt"
    docker_app: "mosquitomqtt.camp.cozzo.net" 
    docker_host: "docker05.camp.cozzo.net" 
    proxy_urls: 
      - "mosquitomqtt.cozzo.net"
      - "mqtt.cozzo.net"
      - "mqtt.camp.cozzo.net"
      - "camp-mqtt.cozzo.net"
      - "camp-mosquitomqtt.cozzo.net"
    proxy_pass: "mosquittomqtt:1883"
    proxy_server: "camp.cozzo.net" 
    proxy: false
    public: false

  - name: "grafana"
    docker_app: "grafana.camp.cozzo.net" 
    docker_host: "docker05.camp.cozzo.net" 
    proxy_urls: 
      - "grafana.cozzo.net"
      - "camp-grafana.cozzo.net"
    proxy_pass: "grafana:3001"
    proxy_server: "camp.cozzo.net" 
    proxy: true
    public: false

  - name: "influxdb"
    docker_app: "influxdb.camp.cozzo.net" 
    docker_host: "docker05.camp.cozzo.net" 
    proxy_urls: 
      - "influxdb.cozzo.net"
      - "camp-influxdb.cozzo.net"
    proxy_pass: "influxdb:8086"
    proxy_server: "camp.cozzo.net" 
    proxy: true
    public: false

  - name: "frigate"
    docker_app: "frigate.camp.cozzo.net" 
    docker_host: "docker05.camp.cozzo.net" 
    proxy_urls: 
      - "frigate.cozzo.net"
      - "camp-frigate.cozzo.net"
    proxy_pass: "frigate:5000"
    proxy_server: "camp.cozzo.net" 
    proxy: true
    public: false

#############################################################
# Datacenter 
  - name: "heimdall"
    docker_app: "heimdall.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls: 
      - "heimdall.cozzo.net"
      - "dc-heimdall.cozzo.net"
      - "dashboard.cozzo.net"
      - "dash.cozzo.net"
    proxy_pass: "heimdall.dc.cozzo.net:9118"
    proxy_server: "dc.cozzo.net"
    proxy: true
    public: false

  - name: "kuma"
    docker_app: "kuma.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls:
      - "kuma.cozzo.net"
      - "dc-kuma.cozzo.net"
      - "uptime.cozzo.net"
      - "status.cozzo.net"
    proxy_pass: "kuma.dc.cozzo.net:3001"
    proxy_server: "dc.cozzo.net" 
    proxy: true
    public: true

  - name: "prowlarr"
    docker_app: "prowlarr.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls: 
      - "prowlarr.cozzo.net"
      - "dc-prowlarr.cozzo.net"
    proxy_pass: "prowlarr.dc.cozzo.net:9696"
    proxy_server: "dc.cozzo.net" 
    proxy: true
    public: false

  - name: "radarr"
    docker_app: "radarr.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls: 
      - "radarr.cozzo.net"
      - "dc-radarr.cozzo.net"
    proxy_pass: "radarr:7878"
    proxy_server: "dc.cozzo.net" 
    proxy: true
    public: false

  - name: "radarr4k"
    docker_app: "radarr4k.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls: 
      - "radarr4k.cozzo.net"
      - "dc-radarr4k.cozzo.net"
    proxy_pass: "radarr4k:7877"
    proxy_server: "dc.cozzo.net" 
    proxy: true
    public: false

  - name: "sonarr"
    docker_app: "sonarr.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls: 
      - "sonarr.cozzo.net"
      - "dc-sonarr.cozzo.net"
    proxy_pass: "http://sonarr.dc.cozzo.net:8989"
    proxy_server: "dc.cozzo.net" 
    proxy: true
    public: false

  - name: "sonarr4k"
    docker_app: "sonarr4k.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls: 
      - "sonarr4k.cozzo.net"
      - "dc-sonarr4k.cozzo.net"
    proxy_pass: "sonarr4k:8988"
    proxy_server: "dc.cozzo.net" 
    proxy: true
    public: false

  - name: "qbittorrent"
    docker_app: "qbittorrent.dc.cozzo.net" 
    docker_host: "downloader02.dc.cozzo.net" 
    proxy_urls: 
      - "qbittorrent.cozzo.net"
      - "dc-qbittorrent.cozzo.net"
    proxy_pass: "qbittorrent.dc.cozzo.net:8080"
    proxy_server: "dc.cozzo.net" 
    proxy: true
    public: false

  - name: "sabnzbd"
    docker_app: "sabnzbd.dc.cozzo.net" 
    docker_host: "downloader02.dc.cozzo.net" 
    proxy_urls: 
      - "sabnzbd.cozzo.net"
      - "dc-sabnzbd.cozzo.net"
      - "sab.cozzo.net"
    proxy_pass: "sabnzbd.dc.cozzo.net:8081"
    proxy_server: "dc.cozzo.net"
    proxy: true
    public: false

  - name: "tautulli"
    docker_app: "tautulli.dc.cozzo.net" 
    docker_host: "downloader03.dc.cozzo.net" 
    proxy_urls: 
      - "tautulli.cozzo.net"
      - "dc-tautulli.cozzo.net"
    proxy_pass: "tautulli.dc.cozzo.net:8181"
    proxy_server: "dc.cozzo.net"
    proxy: true
    public: false

  - name: "ombi"
    docker_app: "ombi.dc.cozzo.net" 
    docker_host: "downloader03.dc.cozzo.net" 
    proxy_urls: 
      - "ombi.cozzo.net"
      - "dc-ombi.cozzo.net"
    proxy_pass: "ombi.dc.cozzo.net:3579"
    proxy_server: "dc.cozzo.net"
    proxy: true
    public: false

  - name: "bazarr"
    docker_app: "bazarr.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls: 
      - "bazarr.cozzo.net"
      - "dc-bazarr.cozzo.net"
      - "subtitles.cozzo.net"
    proxy_pass: "bazarr.dc.cozzo.net:6767"
    proxy_server: "dc.cozzo.net"
    proxy: true
    public: false

  - name: "readarr"
    docker_app: "readarr.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls: 
      - "readarr.cozzo.net"
      - "dc-readarr.cozzo.net"
    proxy_pass: "readarr.dc.cozzo.net:8787"
    proxy_server: "dc.cozzo.net"
    proxy: true
    public: false

  - name: "listenarr"
    docker_app: "listenarr.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls: 
      - "listenarr.cozzo.net"
      - "dc-listenarr.cozzo.net"
    proxy_pass: "listenarr.dc.cozzo.net:8788"
    proxy_server: "dc.cozzo.net"
    proxy: true
    public: false

  - name: "recyclearr"
    docker_app: "recyclarr.dc.cozzo.net" 
    docker_host: "downloader01.dc.cozzo.net" 
    proxy_urls: 
      - "recyclarr.cozzo.net"
    proxy_pass: "recyclarr.dc.cozzo.net:1001"
    proxy_server: "dc.cozzo.net"
    proxy: true
    public: false
