---

- name: Connect to managed zone
  delegate_to: 127.0.0.1
  google.cloud.gcp_dns_managed_zone:
    auth_kind: serviceaccount
    description: Reverse Proxy DNS
    name: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    dns_name: "{{ gcp_dns_name }}"
    service_account_file: "{{ gcp_vars_file }}"
    state: present
  register: gcp_managed_zone

- name: Examine the tags
  delegate_to: 127.0.0.1
  debug:
    msg: '{{ item.1 }} AND {{ item.0.proxy_server }}'
  loop: '{{ proxy_sites | subelements("url") }}'
  #when: acme_challenge[my_idx].changed
  loop_control:
    extended: true
    #index_var: my_idx
  tags:
    - always

- name: Place DNS Records
  delegate_to: 127.0.0.1
  google.cloud.gcp_dns_resource_record_set:
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_vars_file }}"
    managed_zone: "{{ gcp_managed_zone }}"
    type: CNAME
    ttl: 300
    #name: "{{ item.1 }}."
    name: "nginx.cozzo.net."
    #target: "{{ item.0.proxy_server }}"
    target: "dc.cozzo.net."
    state: present
  #loop: '{{ proxy_sites | subelements("url") }}'
  #loop_control:
  #  index_var: my_idx
  #register: stderr

#- name: Pause for 60 seconds to let dns update
#  pause:
#    seconds: 60

