---
# Run this after setting up the host. Pull new compose files and start
# Configures all rquired parts to run containers

#- name: Configure storage
#  hosts: downloader
#  roles:
#    - ubuntu-docker-storage
#  #tags:
#  #  - users-new
#  #  - never
#  become: yes

- name: Configure and git clone
  hosts:
    - downloader
    - plex
  roles:
    - docker-git
  #tags:
  #  - users-new
  #  - never
  become: yes

#- name: Configure docker host
#  hosts:
#    - downloader
#    - plex
#  roles:
#    - docker-host
#  #tags:
#  #  - users-new
#  #  - never
#  become: yes

- name: Configure and run docker containers
  hosts:
    - downloader
    - plex
  roles:
    - docker-start
  #tags:
  #  - users-new
  #  - never
  become: yes
