---
# This play configures the apps on the appropriate reverse proxy caddy servers

# DNS Architecture
# Issues: A record is DYNDNS, AAAA Is mostly static
#
# Proxied: service.cozzo.net CNAME > Reverse Proxy
# Service: service.site.cozzo.net, site-service.cozzo.net
# Server : server.site.cozzo.net, site-server.cozzo.net
# 
# server.site.cozzo.net > A,AAAA
# site-server.cozzo.net > A,AAAA
# service.site.cozzo.net > CNAME > server.site.cozzo.net
# site-service.cozzo.net > CNAME > site-server.cozzo.net
# service.cozzo.net > CNAME > proxy.site.cozzo.net
#
- name: Create Cloud Flare host records
  #hosts: localhost
  hosts:
    #- reverse_proxy
    - localhost
  #connection: local
  roles:
    - dns-cloudflare-hosts
  vars_files:
    - ./group_vars/dns.yml
    - ./group_vars/cloudflare.yml

