---
# Run this after a clean install

- name: Apt physical (PI)
  hosts:
    - raspberry_pi
  roles:
    - apt-upgrade
  #tags:
  #  - sysprep
  #  #- never
  become: yes

- name: Apt VM vmtools
  hosts:
    - virtual_machines
  roles:
    - apt-vmtools
  #tags:
  #  - sysprep
  #  #- never
  become: yes
