---
# This play configures the apps on the appropriate reverse proxy caddy servers

#- name: Configure and git clone
#  hosts:
#    - reverse_proxy
#  roles:
#    - docker-git
#  become: yes

- name: Create DNS records
  #hosts: localhost
  hosts:
    - reverse_proxy
  #connection: local
  roles:
    - google-dns-create-cname
  vars_files:
    - ./group_vars/proxy_sites.yml
    - ./group_vars/docker.yml

#- name: Configure reverse proxy
#  hosts:
#    - reverse_proxy
#  roles:
#    - app-caddy
#  #become: yes
#  vars_files:
#    - ./group_vars/proxy_sites.yml
#    - ./group_vars/docker.yml


