---

- name: Configure and git clone
  hosts:
    - downloader
    - plex
  roles:
    - docker-git
  become: yes

- name: Configure and run docker containers
  hosts:
    - downloader
    - plex
  roles:
    - docker-restart
  become: yes
