---

- name: Configure and git clone
  hosts:
    - downloader
    - plex
    - dev
    - docker_camp
    - docker_md
    - nginx
    - travel_pi
    - docker_infra
  roles:
    - docker-git
  become: yes
