---
# Start docker containers

- name: Configure and git clone
  hosts:
    - downloader
    - plex
    - dev
    - docker_camp
    - docker_md
    - nginx
    - travel_pi
    - docker_dns
  roles:
    - docker-git
  #tags:
  #  - users-new
  #  - never
  become: yes

- name: Configure and run docker containers
  hosts:
    - downloader
    - plex
    - dev
    - docker_camp
    - docker_md
    - nginx
    - travel_pi
    - docker_dns
  roles:
    - docker-start
  #tags:
  #  - users-new
  #  - never
  become: yes
