---
# Run this to configure docker environment
# Configures all rquired parts to run containers

#- name: Configure storage
#  hosts: downloader
#  roles:
#    - ubuntu-docker-storage
#  #tags:
#  #  - users-new
#  #  - never
#  become: yes

#- name: Configure and git clone
#  hosts:
#    - downloader
#    - plex
#  roles:
#    - docker-git
#  #tags:
#  #  - users-new
#  #  - never
#  become: yes

- name: Configure DNS
  hosts:
    - docker_dns
  roles:
    - docker-resolv.conf
  #tags:
  #  - users-new
  #  - never
  become: yes


- name: Configure docker
  hosts:
    - downloader
    - plex
    - docker_camp
    - dev
    - docker_md
    - nginx
    - travel_pi
    - docker_dns
  roles:
    - docker-host
  #tags:
  #  - users-new
  #  - never
  become: yes

- name: Configure docker trident
  hosts:
    - downloader
    - plex
    - dev
  roles:
    - docker-netapp-trident
  #tags:
  #  - users-new
  #  - never
  become: yes


#- name: Configure and run docker containers
#  hosts:
#    - downloader
#    - plex
#  roles:
#    - docker-run
#  #tags:
#  #  - users-new
#  #  - never
#  become: yes
