---
# Stop docker containers

- name: Configure and git clone
  hosts:
    - downloader
    - plex
    - dev
    - docker_camp
    - docker_md
  roles:
    - docker-git
  #tags:
  #  - users-new
  #  - never
  become: yes

- name: Stop docker containers
  hosts:
    - downloader
    - plex
    - dev
    - docker_camp
    - docker_md
  roles:
    - docker-stop
  #tags:
  #  - users-new
  #  - never
  become: yes
