---
# Run this after a clean install
# Configures all rquired parts to run containers

- name: Configure storage DC
  hosts:
    - downloader
    - plex
    - dev
  #- nginx
  roles:
    - ubuntu-docker-storage-dc
    - ubuntu-docker-glusterfs
  #tags:
  #  - users-new
  #  - never
  become: yes

- name: Configure storage Camp
  hosts:
    - docker_camp
  #- nginx
  roles:
    - ubuntu-docker-storage-camp
  #tags:
  #  - users-new
  #  - never
  become: yes

- name: Configure storage MD
  hosts:
    - docker_md
  #- nginx
  roles:
    - ubuntu-docker-storage-md
  #tags:
  #  - users-new
  #  - never
  become: yes


#- name: Configure and git clone
#  hosts: downloader
#  roles:
#    - docker-git
#  #tags:
#  #  - users-new
#  #  - never
#  become: yes
#
#- name: Configure docker host
#  hosts: downloader
#  roles:
#    - docker-host
#  #tags:
#  #  - users-new
#  #  - never
#  become: yes
#
#- name: Configure and run docker containers
#  hosts: downloader
#  roles:
#    - docker-run
#  #tags:
#  #  - users-new
#  #  - never
#  become: yes
