---
# restart containers. Actually restart not stop, start

- name: Configure and git clone
  hosts:
    - downloader
    - plex
    - docker_camp
    - docker_md
    - nginx
    - travel_pi
    - docker_dns
  roles:
    - docker-git
  become: yes

- name: Configure and run docker containers
  hosts:
    - downloader
    - plex
    - docker_camp
    - docker_md
    - nginx
    - travel_pi
    - docker_dns
  roles:
    - docker-update
  become: yes
