---

- name: Configure and git clone
  hosts:
    - reverse_proxy
    - downloader
    - plex
    - dev
    - docker_camp
    - docker_md
    - nginx
    - travel_pi
    - dns01
    - dns02
  roles:
    - docker-git
  become: yes
