---

- name: Configure and git clone
  hosts:
    - downloader
    - plex
    - dev
    - docker_camp
    - docker_md
  roles:
    - docker-git
  become: yes

- name: Configure and run docker containers
  hosts:
    - downloader
    - plex
    - dev
    - docker_camp
    - docker_md
  roles:
    - docker-restart
  become: yes
