---
# This playbook contains common plays that will be run on all nodes.

- name: "Remove the build account"
  user:
    name: "usr-build"
    comment: "Delete build user"
    state: absent
    remove: yes
#  become: yes
  #become_user: "{{ ansible_user }}"
  #ansible_ssh_user: "{{ ansible_user }}"
  #tags:
  #  - never
  #  - cleanuser

- name: "Remove the build account"
  user:
    name: "ubuntu"
    comment: "Delete build user"
    state: absent
    remove: yes
