---
# This should update git on the destination server.

#- name: Remove git folder
#  file:
#    path: /mnt/git/docker
#    state: absent
#    #owner: 'mattcozzolino'
#    #group: 'mattcozzolino'
#  become: yes
##  become_user: mattcozzolino
#  tags:
#    - never
#    - install

- name: Make sure we have the GIT ssh keypair
  template:
    src: "{{ item.src }}"
#    dest: /home/mattcozzolino/resolv.conf
    dest: "{{ item.dst }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ item.mode }}"
#  notify:
#    - Reboot host
  with_items:
    #- { src: "../../vars/ssh-git.key",    dst: "/home/{{ ansible_user }}/.ssh/ssh-git.key", mode: "0600" }
    #- { src: "../../vars/ssh-git.pub",    dst: "/home/{{ ansible_user }}/.ssh/ssh-git.pub", mode: "0644" }
    - { src: "../../vars/ssh-git-ro.key", dst: "/home/{{ ansible_user }}/.ssh/ssh-git-ro.key", mode: "0600" }
    - { src: "../../vars/ssh-git-ro.pub", dst: "/home/{{ ansible_user }}/.ssh/ssh-git-ro.pub", mode: "0644" }
  #with_items:
  #  - { path: '/home/{{ ansible_user }}/.ssh/id_rsa',     mode: '0600' }
  #  - { path: '/home/{{ ansible_user }}/.ssh/id_rsa.pub', mode: '0644' }
  tags:
    - user
  #become: yes
  #become_user: "{{ ansible_user }}"

#- name: chmod SSH key
#  file:
#    path: "{{ item.path }}"
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
#    mode: "{{ item.mode }}"
#  with_items:
#    - { path: '/home/{{ ansible_user }}/.ssh/ssh-git.key', mode: '0600' }
#    - { path: '/home/{{ ansible_user }}/.ssh/ssh-git.pub', mode: '0644' }
#  tags:
#    - user
#  #become: yes
#  #become_user: "{{ ansible_user }}"


- name: Validate local Git folder exists
  file:
    path: /mnt/git/docker
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes
##  become_user: mattcozzolino
#  tags:
#    - never
#    - install

- name: Update docker-compose from git
  git:
    accept_hostkey: true
    repo: git@github.com:mcozzo/docker.git
    dest: /mnt/git/docker
    update: true
    version: HEAD
    force: true
    remote: origin
    key_file: "/home/{{ ansible_user }}/.ssh/ssh-git-ro.key"
  become: true
  become_user: "{{ ansible_user }}"
#  tags:
#    - never
##    - update
#    - install
